language: ruby
rvm:
  - 1.9.3
  - 2.0.0
bundler_args: --without development
branches:
  only:
    - master
script: rake spec
before_script:
  - cp -f config/database.travis.yml config/database.yml
  - RAILS_ENV=test rake db:create db:schema:load --trace
